// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: infinispan/hotrod/protobuf/base_types.proto

#ifndef PROTOBUF_infinispan_2fhotrod_2fprotobuf_2fbase_5ftypes_2eproto__INCLUDED
#define PROTOBUF_infinispan_2fhotrod_2fprotobuf_2fbase_5ftypes_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include <infinispan/hotrod/ImportExport.h>
// @@protoc_insertion_point(includes)

namespace infinispan {
namespace hotrod {
namespace protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_infinispan_2fhotrod_2fprotobuf_2fbase_5ftypes_2eproto();
void protobuf_AssignDesc_infinispan_2fhotrod_2fprotobuf_2fbase_5ftypes_2eproto();
void protobuf_ShutdownFile_infinispan_2fhotrod_2fprotobuf_2fbase_5ftypes_2eproto();

class HR_EXTERN base_types;

// ===================================================================

class base_types : public ::google::protobuf::Message {
 public:
  base_types();
  virtual ~base_types();

  base_types(const base_types& from);

  inline base_types& operator=(const base_types& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const base_types& default_instance();

  void Swap(base_types* other);

  // implements Message ----------------------------------------------

  base_types* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const base_types& from);
  void MergeFrom(const base_types& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 i64 = 3;
  inline bool has_i64() const;
  inline void clear_i64();
  static const int kI64FieldNumber = 3;
  inline ::google::protobuf::int64 i64() const;
  inline void set_i64(::google::protobuf::int64 value);

  // optional int32 i32 = 5;
  inline bool has_i32() const;
  inline void clear_i32();
  static const int kI32FieldNumber = 5;
  inline ::google::protobuf::int32 i32() const;
  inline void set_i32(::google::protobuf::int32 value);

  // optional string str = 9;
  inline bool has_str() const;
  inline void clear_str();
  static const int kStrFieldNumber = 9;
  inline const ::std::string& str() const;
  inline void set_str(const ::std::string& value);
  inline void set_str(const char* value);
  inline void set_str(const char* value, size_t size);
  inline ::std::string* mutable_str();
  inline ::std::string* release_str();
  inline void set_allocated_str(::std::string* str);

  // @@protoc_insertion_point(class_scope:infinispan.hotrod.protobuf.base_types)
 private:
  inline void set_has_i64();
  inline void clear_has_i64();
  inline void set_has_i32();
  inline void clear_has_i32();
  inline void set_has_str();
  inline void clear_has_str();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 i64_;
  ::std::string* str_;
  ::google::protobuf::int32 i32_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_infinispan_2fhotrod_2fprotobuf_2fbase_5ftypes_2eproto();
  friend void protobuf_AssignDesc_infinispan_2fhotrod_2fprotobuf_2fbase_5ftypes_2eproto();
  friend void protobuf_ShutdownFile_infinispan_2fhotrod_2fprotobuf_2fbase_5ftypes_2eproto();

  void InitAsDefaultInstance();
  static base_types* default_instance_;
};
// ===================================================================


// ===================================================================

// base_types

// optional int64 i64 = 3;
inline bool base_types::has_i64() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void base_types::set_has_i64() {
  _has_bits_[0] |= 0x00000001u;
}
inline void base_types::clear_has_i64() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void base_types::clear_i64() {
  i64_ = GOOGLE_LONGLONG(0);
  clear_has_i64();
}
inline ::google::protobuf::int64 base_types::i64() const {
  return i64_;
}
inline void base_types::set_i64(::google::protobuf::int64 value) {
  set_has_i64();
  i64_ = value;
}

// optional int32 i32 = 5;
inline bool base_types::has_i32() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void base_types::set_has_i32() {
  _has_bits_[0] |= 0x00000002u;
}
inline void base_types::clear_has_i32() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void base_types::clear_i32() {
  i32_ = 0;
  clear_has_i32();
}
inline ::google::protobuf::int32 base_types::i32() const {
  return i32_;
}
inline void base_types::set_i32(::google::protobuf::int32 value) {
  set_has_i32();
  i32_ = value;
}

// optional string str = 9;
inline bool base_types::has_str() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void base_types::set_has_str() {
  _has_bits_[0] |= 0x00000004u;
}
inline void base_types::clear_has_str() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void base_types::clear_str() {
  if (str_ != &::google::protobuf::internal::kEmptyString) {
    str_->clear();
  }
  clear_has_str();
}
inline const ::std::string& base_types::str() const {
  return *str_;
}
inline void base_types::set_str(const ::std::string& value) {
  set_has_str();
  if (str_ == &::google::protobuf::internal::kEmptyString) {
    str_ = new ::std::string;
  }
  str_->assign(value);
}
inline void base_types::set_str(const char* value) {
  set_has_str();
  if (str_ == &::google::protobuf::internal::kEmptyString) {
    str_ = new ::std::string;
  }
  str_->assign(value);
}
inline void base_types::set_str(const char* value, size_t size) {
  set_has_str();
  if (str_ == &::google::protobuf::internal::kEmptyString) {
    str_ = new ::std::string;
  }
  str_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* base_types::mutable_str() {
  set_has_str();
  if (str_ == &::google::protobuf::internal::kEmptyString) {
    str_ = new ::std::string;
  }
  return str_;
}
inline ::std::string* base_types::release_str() {
  clear_has_str();
  if (str_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = str_;
    str_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void base_types::set_allocated_str(::std::string* str) {
  if (str_ != &::google::protobuf::internal::kEmptyString) {
    delete str_;
  }
  if (str) {
    set_has_str();
    str_ = str;
  } else {
    clear_has_str();
    str_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace hotrod
}  // namespace infinispan

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_infinispan_2fhotrod_2fprotobuf_2fbase_5ftypes_2eproto__INCLUDED
