# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/samuele/Documents/sia/workspaceIspn/HotRod@cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/samuele/Documents/sia/workspaceIspn/HotRod@cpp

# Include any dependencies generated for this target.
include test/swig/CMakeFiles/../../src/hotrod/api/Configuration.cpp.dir/depend.make

# Include the progress variables for this target.
include test/swig/CMakeFiles/../../src/hotrod/api/Configuration.cpp.dir/progress.make

# Include the compile flags for this target's objects.
include test/swig/CMakeFiles/../../src/hotrod/api/Configuration.cpp.dir/flags.make

test/swig/CMakeFiles/../../src/hotrod/api/Configuration.cpp.dir/requires:
.PHONY : test/swig/CMakeFiles/../../src/hotrod/api/Configuration.cpp.dir/requires

test/swig/CMakeFiles/../../src/hotrod/api/Configuration.cpp.dir/clean:
	cd /home/samuele/Documents/sia/workspaceIspn/HotRod@cpp/test/swig && $(CMAKE_COMMAND) -P CMakeFiles/../../src/hotrod/api/Configuration.cpp.dir/cmake_clean.cmake
.PHONY : test/swig/CMakeFiles/../../src/hotrod/api/Configuration.cpp.dir/clean

test/swig/CMakeFiles/../../src/hotrod/api/Configuration.cpp.dir/depend:
	cd /home/samuele/Documents/sia/workspaceIspn/HotRod@cpp && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/samuele/Documents/sia/workspaceIspn/HotRod@cpp /home/samuele/Documents/sia/workspaceIspn/HotRod@cpp/test/swig /home/samuele/Documents/sia/workspaceIspn/HotRod@cpp /home/samuele/Documents/sia/workspaceIspn/HotRod@cpp/test/swig /home/samuele/Documents/sia/workspaceIspn/HotRod@cpp/test/src/hotrod/api/Configuration.cpp.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : test/swig/CMakeFiles/../../src/hotrod/api/Configuration.cpp.dir/depend

